hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 100000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 5000

feign:
  hystrix:
    enabled: true

zuul:
#  sensitiveHeaders: Cookie,Set-Cookie
#  host:
#    connect-timeout-millis: 20000
#    socket-timeout-millis: 20000
  routes:
    auth-service:
      path: /uaa/**
      serviceId: mss-auth
      stripPrefix: true
      sensitiveHeaders:
    admin-service:
      path: /admin/**
      serviceId: mss-admin
      stripPrefix: true
      sensitiveHeaders:
    api-b:
      path: /api-b/**
      url: http://localhost:8765/
    simple163:
      url: https://www.baidu.com/
    registry:
      url: http://mss-registry:8761/
server:
  port: 4000
  tomcat:
    max-http-header-size: 8192
